### ISSUE TITLE
Why isn't JPG supported?

### ISSUE THREAD

**Issue by jlafitte** [Creatiwity/nativescript-images-generator-hook#1]
Looking through the code, it seems like it would be pretty easy to add JPG support.  Is there a reason it is only restricted to PNG?  If not, I might submit a pull request at some point.  I'm a little swamped currently, but should be doable eventually.

**Comment by JohanDufau** [comment]
Hey!
You are right and we should handle the extension of the entry file. Feel free to submit a PR!
