### ISSUE TITLE
Plugin seems to be broken

### ISSUE THREAD

**Issue by NilsFiedlerOTRS** [Creatiwity/nativescript-images-generator-hook#3]
After installing the plugin I ran my project using ``tns run ios`. Unfortunately teh console shows this error:

``Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (ios)
Unexpected token {``

**Comment by julien1619** [comment]
Can you copy paste your package.json or at least the versions you use? Thanks.

**Comment by NilsFiedlerOTRS** [comment]
Bonjour Julien.

I copied my package.json but I removed your plugin already...


>>>
{
…repo-specific-info deleted...
  "nativescript": {
    "id": "mobile.xxx",
    "templateVersion": "v2",
    "tns-android": {
      "version": "6.3.1"
    },
    "tns-ios": {
      "version": "6.3.0"
    }
  },
  "scripts": {
    "pretest": "eslint --ignore-path .gitignore .",
    "test": "jest",
    "unit": "npm test",
    "build": "tns build"
  },
  "dependencies": {
    "@vue/devtools": "^5.0.6",
    "js-base64": "^2.5.2",
    "nativescript-randombytes": "^1.0.0",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-socketio": "^3.2.1",
    "nativescript-toasty": "^1.3.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^6.3.2",
    "uuid": "^3.4.0",
    "vuex": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@vue/test-utils": "^1.0.0-beta.30",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^10.0.3",
    "babel-jest": "^24.9.0",
    "babel-loader": "^8.0.2",
    "bufferutil": "^4.0.1",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.20.0",
    "eslint-plugin-jest": "^23.6.0",
    "eslint-plugin-vue": "^6.1.2",
    "husky": "^4.0.10",
    "jest": "^24.9.0",
    "nativescript-dev-webpack": "^1.4.1",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.13.1",
    "typescript": "^3.7.4",
    "utf-8-validate": "^5.0.2",
    "vue": "^2.6.11",
    "vue-jest": "^3.0.5",
    "vue-loader": "^15.4.0",
    "vue-template-compiler": "^2.6.11"
  },
  "husky": {
    "hooks": {
      "pre-commit": ""
    }
  }
}

<<<

**Comment by NilsFiedlerOTRS** [comment]
I just stumbled upon you using crypto.createHash('md5'); in explorer.js.
I had a lot of trouble using the crypto-plugin in NativeScript. I only needed to base64 encode a string and had to use nativescript-randombytes plugin  and a shim to make it happen.
How did you manage to use it?

**Comment by JohanDufau** [comment]
Hello,
I cannot reproduce your issue.
Can you retry and tell me if you still have the error? If yes, can you provide your node version, macOS version and try to have the entire error message from the log file?

Thank you!

**Comment by NilsFiedlerOTRS** [comment]
Unfortunately I can’t help you there anymore due to other things Im working on, now. I appreciate your efforts. I was working on macOS 10.14.16, node 8.16.2

**Comment by JohanDufau** [comment]
Ok, maybe it was linked to node8 at the time. I'm working on node13 right now.
If you retry this plugin in the future, I'm interested having your feedback again.
Thx!

**Comment by NilsFiedlerOTRS** [comment]
Of course
